name: shopping_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5 
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter_bloc: ^8.1.6
  flutter_lints: ^4.0.0
  get_it: ^7.7.0
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1

  # all packages go here
  # core:
  #   path: ../../core
  authentication:
    path: ../../Packages/authentication

  # authentication:
  #   git:
  #     url: 
  core:
    git:
      url: https://github.com/remith/core.git


dependency_overrides:
  core:
    git:
      url: https://github.com/remith/core.git

dev_dependencies:
  flutter_test:
    sdk: flutter  
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
 
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - assets/general/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
